version: '3.5'

services:
  grafana:
    image: jenkins/jenkins:jdk21
    container_name: jenkins
    hostname: jenkins
    restart: always
    privileged: true
    user: root
    environment:
      - TZ=Asia/Dhaka
    ports:
      - '8282:8080'
      - '50000:50000'
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      dkr_net:

volumes:
  jenkins_home:
    name: jenkins_home

networks:
  dkr_net:
    external: true
