version: '3.5'

services:
  klnkserverfree:
    image: kiloview/kilolinkserverfree:latest
    container_name: klnkserverfree
    hostname: klnkserverfree
    restart: always
    user: root
    privileged: true
    network_mode: host
    environment:
      - TZ=Asia/Dhaka
    volumes:
      - klnkserverfree_config:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  klnkserverfree_config:
    name: klnkserverfree_config
