version: '3.5'

services:
  truecommand:
    image: 'ixsystems/truecommand:latest'
    container_name: truecommand
    hostname: truecommand
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dhaka
    ports:
      - '4000:80'
      - '4443:443'
    volumes:
      - truecommand_data:/data
    networks:
      dkr_net:

volumes:
  truecommand_data:
    name: truecommand_data

networks:
  dkr_net:
    external: true
