version: '3.5'

services:
  kvaudiosvr:
    image: kiloview/kvaudiosvr:latest
    container_name: kvaudiosvr
    hostname: kvaudiosvr
    restart: always
    user: root
    privileged: true
    network_mode: host
    environment:
      - TZ=Asia/Dhaka
    volumes:
      - kvaudiosvr_config:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  kvaudiosvr_config:
    name: kvaudiosvr_config
