version: '3.5'

services:
  adguardhome:
    image: 'adguard/adguardhome'
    container_name: adguardhome
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dhaka
    ports:
      # plain DNS
      - '53:53/tcp'
      - '53:53/udp'
      # add if you intend to use AdGuard Home as a DHCP server
      - '67:67/udp'
      - '68:68/tcp'
      - '68:68/udp'
      # add if you are going to run AdGuard Home as an HTTPS/DNS-over-HTTPS server
      - '80:80/tcp'
      - '443:443/tcp'
      - '443:443/udp'
      - '3000:3000/tcp'
      # add if you are going to run AdGuard Home as a DNS-over-TLS server
      - '853:853/tcp'
      # add if you are going to run AdGuard Home as a DNS-over-QUIC server
      - '784:784/udp'
      - '853:853/udp'
      - '8853:8853/udp'
      # add if you are going to run AdGuard Home as a DNSCrypt server
      - '5443:5443/tcp'
      - '5443:5443/udp'
    volumes:
      - adguardhome_data:/opt/adguardhome/work
      - adguardhome_config:/opt/adguardhome/conf
    networks:
      ipvlan_net:
        ipv4_address: x.x.x.x

volumes:
  adguardhome_data:
    name: adguardhome_data
  adguardhome_config:
    name: adguardhome_config

networks:
  ipvlan_net:
    external: true
