version: '3.5'

services:
  dashy_srv01:
    image: 'linuxserver/heimdall:latest'
    container_name: dashy_srv01
    hostname: dashy-srv01.atnnews.local
    restart: always
    privileged: true
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dhaka
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - srv01_data:/config
    networks:
      ipvlan_net:
        ipv4_address: 192.168.100.53
        # ip addr add 192.168.50.53/24 dev eth0 (add it manually)
    dns:
      - 192.168.100.79
      - 192.168.100.1

  dashy_srv02:
    image: 'linuxserver/heimdall:latest'
    container_name: dashy_srv02
    hostname: dashy-srv02.atnnews.local
    restart: always
    privileged: true
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dhaka
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - srv02_data:/config
    networks:
      ipvlan_net:
        ipv4_address: 192.168.100.52
        # ip addr add 192.168.50.52/24 dev eth0 (add it manually)
    dns:
      - 192.168.100.79
      - 192.168.100.1

volumes:
  srv01_data:
    name: srv01_data
  srv02_data:
    name: srv02_data

networks:
  ipvlan_net:
    external: true
