version: '3.5'

services:
  dashy1:
    image: linuxserver/heimdall:latest
    container_name: dashy1
    hostname: dashy1.atnnews.local
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dhaka
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - dashy1_data:/config
    networks:
      ipvlan_net:
        ipv4_address: 192.168.100.52
    dns:
      - 192.168.100.79
      - 192.168.100.1

  dashy2:
    image: linuxserver/heimdall:latest
    container_name: dashy2
    hostname: dashy2.atnnews.local
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dhaka
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - dashy2_data:/config
    networks:
      ipvlan_net:
        ipv4_address: 192.168.100.53
    dns:
      - 192.168.100.79
      - 192.168.100.1

volumes:
  dashy1_data:
    name: dashy1_data
  dashy2_data:
    name: dashy2_data

networks:
  ipvlan_net:
    external: true
